### ISSUE TITLE
Missing fields from CSR images

### ISSUE THREAD

**Issue by rajnesh-kanwal** [riscv/riscv-cfi#109]
My generated PDF seems to be missing the CSR fields. Any ideas what might be causing this?
It works if I change the image type from png to svg.

> --- a/cfi_csrs.adoc
> +++ b/cfi_csrs.adoc
> @@ -6,7 +6,7 @@ This chapter specifies the CSR state of the Zicfisslp extension.
>  === Machine environment configuration registers (`menvcfg and menvcfgh`)
>  
>  .Machine environment configuration register (`menvcfg`) for MXLEN=64
> -[wavedrom, , ]
> +[wavedrom, ,svg]
>  ....
>  {reg: [
> 

![image](https://github.com/riscv/riscv-cfi/assets/72204611/9fdf4595-f80e-4083-95d7-db2338c7b5c3)

My setup:
Ubuntu 20.04
wavedrom 2.6.8
Asciidoctor 2.0.20
asciidoctor-diagram 2.2.9

**Comment by ved-rivos** [comment]
Thanks for spotting the issue. Would you like to send me a PR for this?

**Comment by ved-rivos** [comment]
Thanks.
