### ISSUE TITLE
Proposal: Add dependency to `Zicsr`

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-cfi#14]
This is the same series of proposals (add dependency to `Zicsr` from unprivileged extensions with CSR):

*   riscv/riscv-code-size-reduction#179 (Resolved)
*   riscv/riscv-p-spec#145 (will be reflected)
*   riscv/riscv-j-extension#17 (opened)

Although `Zisslpcfi` has privileged part (all privileged extensions have indirect dependency to `Zicsr` through the privileged architecture), this extension contains user-accessible CSRs.  So, adding `Zicsr` to the dependency would be nice and clearer (for toolchains implementing this `Zisslpcfi` extension).

**Comment by ved-rivos** [comment]
Agree. Added by PR #15
