### ISSUE TITLE
Do coroutines need special handling?

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-cfi#143]
The RISC-V unprivileged spec has the following for JALR:

| rd is x1/x5 | rs1 is x1/x5 | rd=rs1 | RAS action | Notes |
|-|-|-|-|-|
| No | No | - | None | Tail call |
| No | Yes | - | Pop | Return |
| Yes | No | - | Push | Call |
| Yes | Yes | No | Pop, then push | Co-routine call |
| Yes | Yes | Yes | Push | Call |

Extending this with rs1 is x7 and is_lp_expected gives, I believe:

| rd is x1/x5 | rs1 is x1/x5 | rd=rs1 | rs1 is x7 | RAS action | is_lp_expected | Notes |
|-|-|-|-|-|-|-|
| No | No | - | No | None | Yes | Protected tail call |
| No | No | - | Yes | None | No | Unprotected tail call |
| No | Yes | - | -  | Pop | No | Unprotected return (use shadow stack) |
| Yes | No | - | No | Push | Yes | Protected call |
| Yes | No | - | Yes | Push | No | Unprotected call |
| Yes | Yes | No | - | Pop, then push | No | Unprotected co-routine call |
| Yes | Yes | Yes | - | Push | No | Unprotected call |

For forward edges you can therefore express:
* Protected tail call (rd != x1/x5, rs1 != x1/x5/x7)
* Unprotected tail call (rd != x1/x5, rs1 = x7)
* Protected call (rd = x1/x5, rs1 != x1/x5/x7)
* Unprotected call (rd = x1/x5, rs1 = x1/x5/x7, rs1 = x7/rd)
* Unprotected co-routine call (rd = x1/x5, rs1 = x1/x5, rs1 != rd)

What's missing is the ability to express a protected co-routine call. Is this intended? JALR goes out of its way to specify encodings for co-routines. In general co-routine resumption probably looks more shadow-stack-y than landing-pad-y, but co-routine starting isn't, and could be via a function pointer-like quantity.

**Comment by ved-rivos** [comment]
The `rd = x1|x5, rs1 = x1|x5, rs1 != rd` hint is most useful case where two subroutines are continually "returning" to their resumption point. Doing a "pop followed by a push" on the return address prediction stack keeps the "resume" address of the coroutines resumption location at the top of the stack - without the pop it would underflow. So through these "return" ping pongs - which you rightly noted is "shadow stacky" they keep replacing the top of the return address prediction stack and when eventually they are done there is one misprediction but the rest of the return address prediction stack leading to this coroutine sequence is preserved. This was intended and nothing special was needed for this case.

**Comment by jrtc27** [comment]
Yes. But what about the initial “call into a coroutine” case? That may need protection.

**Comment by ved-rivos** [comment]
The initial call should be using a regular indirect call since the coroutine entry point would be address taken and this call will need to land on the landing pad. `swapcontext` on x86 for example differentiates between the initial case and the return case for that reason.
