### ISSUE TITLE
Typo for Zcmop instruction

### ISSUE THREAD

**Issue by kacouane** [riscv/riscv-cfi#172]
I think there is a typo for the Zcmop number example the compressed C.sspush is noted as using Zcmop.1 encoding when it is Zcmop.0

![image](https://github.com/riscv/riscv-cfi/assets/61777902/b44de9d0-65bd-4a24-8709-76ce024c8c6a)

**Comment by ved-rivos** [comment]
The description follows the latest updated Zcmop specification. I believe the quoted version is stale.

![image](https://github.com/riscv/riscv-cfi/assets/91900059/5e3a500d-3799-4af5-8498-dceae9e1e713)

**Comment by kacouane** [comment]
ok sorry didn't know there was a new version for Zimop thanks
