### ISSUE TITLE
SSAMOSWAP use same encoding as AMOCAS.

### ISSUE THREAD

**Issue by yetingk** [riscv/riscv-cfi#176]
It seems that [SSAMOSWAP] uses same encoding as [AMOCAS]. 

[SSAMOSWAP]: https://github.com/riscv/riscv-cfi/blob/main/cfi_backward.adoc#atomic-swap-from-a-shadow-stack-location
[AMOCAS]: https://github.com/riscv/riscv-zacas/blob/main/zacas.adoc

**Comment by ved-rivos** [comment]
That is a typo. `ssamoswap` should use code `01001` and not `00101`. FIxed in PR #177
