### ISSUE TITLE
SSAMOSWAP in chapter 2.2

### ISSUE THREAD

**Issue by jklockars** [riscv/riscv-cfi#189]
Currently there is no mention of SSAMOSWAP in chapter 2.2.
Shouldn't there be text saying that it is an illegal instruction when the various xSSE are 0?

**Comment by ved-rivos** [comment]
The rules for `SSAMOSWAP` are specified in listing 4 and 5. 
```
if privilege_mode != M && menvcfg.SSE == 0
    raise illegal-instruction exception
if S-mode not implemented
    raise illegal-instruction exception
else if privilege_mode == U && senvcfg.SSE == 0
    raise illegal-instruction exception
else if privilege_mode == VS && henvcfg.SSE == 0
    raise virtual instruction exception
else if privilege_mode == VU && senvcfg.SSE == 0
    raise virtual instruction exception
else
   <<swap>>
```

The `SSAMOSWAP`, unlike other shadow stack instructions are not Zimop. Further, while `xSSE` is always 0 in machine mode, the machine mode may use `SSAMOSWAP` to operate on memory of lower privileges using `MPRV` and `MPP` to provide the effective privilege mode for the memory access.

**Comment by ved-rivos** [comment]
Perhaps I  misunderstood your comment. Were you suggesting to add statements in section 2.2 explaining the faults in listing 4/5?

**Comment by jklockars** [comment]
I am aware of the rules in chapter 2.7 (implemented this last week ;-).
Obviously, that is enough to describe the behaviour.

But for example SSRDP is described in 2.6 as doing
```
if (xSSE == 1)
  X(dst) = ssp
else
  X(dst) = 0
endif
```
even though 2.2 already says what happens when xSSE = 0. 
So why not similar treatment for SSAMOSWAP in 2.2?

**Comment by ved-rivos** [comment]
Please check PR #193
