### ISSUE TITLE
Shadow stack memory protection in bare mode

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-cfi#197]
The spec said:
> If satp.MODE (or vsatp.MODE when V=1) is set to Bare and the effective privilege mode is below M, shadow stack memory accesses are prohibited, and shadow stack instructions will raise a store/AMO access-fault exception.

Can I interpret that normal load and store accesses below M mode in bare mode also raise store/AMO access-fault exceptions? But how the privilege modes below M in bare mode could know the memory address located at SS page without translation?

**Comment by ved-rivos** [comment]
> Can I interpret that normal load and store accesses below M mode in bare mode also raise store/AMO access-fault exceptions?

No. Only shadow stack memory accesses are prohibited. Shadow stack memory accesses can only be generated by shadow stack instructions. Non shadow stack instructions generated non shadow stack memory accesses.

**Comment by ved-rivos** [comment]
Zicfiss is just not usable in Bare mode. When Bare mode is selected, the `sspush`, `sspopchk`, and `ssamoswap` will just cause an access fault and lead to the program being terminated. The OS cannot select Bare for user more without selecting Bare for supervisor as well since virtual memory system is not U/S mode specific.

**Comment by ved-rivos** [comment]
> The malicious program of user mode can modify content of shadow stack memory because normal store instructions to shadow stack memory are allowed in Bare mode.

A variety of security issues can arise in this scenario, as the disabling of virtual memory address translation and protection mechanisms exposes critical assets. For instance, a user mode program could modify the operating system's code and data. This capability enables the program to execute malicious actions directly, obviating the need for control flow subversion attacks like Return-Oriented Programming (ROP) or Jump-Oriented Programming (JOP). In such a scenario, the program could replace its own code or even modify the code and data of other programs, including those with higher privileges (e.g., root processes). When memory protections are disabled, and an attacker is able to make the OS execute this sequence, it typically signifies a complete compromise of system security.

**Comment by ved-rivos** [comment]
We have this guideline in the specification:

>  Operating systems must ensure that no writable, non-shadow-stack alias virtual address mappings exist for the physical memory backing the shadow stack.

**Comment by henry-hsieh** [comment]
Thanks, I missed this. Thanks again.
