### ISSUE TITLE
SS instructions should report store/AMO guest  page fault due to VS stage memory  implicit access check fails

### ISSUE THREAD

**Issue by leBsky** [riscv/riscv-cfi#223]
Hi, the cfi_backward says:
![image](https://github.com/riscv/riscv-cfi/assets/21328365/819384b5-bd74-4dc9-98c6-52061609e7c5)

However, the risc-v priviledged spec says:
![image](https://github.com/riscv/riscv-cfi/assets/21328365/46dbf1fd-f4fb-4f6b-8acb-5619ac4d95ff)

My understanding is that the implicit memory access to support VS-stage translation checks load or store permission depending on if it writes or reads VS-stage page table. However, the final exception should always be store/AMO  guest page fault for SS instructions.

**Comment by ved-rivos** [comment]
@leBsky - You are right that the exception should be reported as a store/AMO guest page fault. This note is incorrect and is removed in https://github.com/riscv/riscv-cfi/pull/222/commits/bd9938ca9cea2bfb72b64d90a6efc41e373a01a3

**Comment by leBsky** [comment]
@ved-rivos Thanks, closed.
