### ISSUE TITLE
Clarifications about SS instructions in Machine mode

### ISSUE THREAD

**Issue by leBsky** [riscv/riscv-cfi#224]
![image](https://github.com/riscv/riscv-cfi/assets/21328365/71060733-86ed-440f-8311-b755bc52e5bd)
Here says " the Use of Zicfiss in M-mode is not supported? But what's the exact bahavior when execute Zicfiss instructions in Machine mode?

First, For sspush/sspopchk instructions, Should they be considered as Zipmop instructions?

Second, For ssamoawap.W/D instructions, here says:
![image](https://github.com/riscv/riscv-cfi/assets/21328365/024f1db9-0c6c-40f4-bf19-15bc8efc6d7c)

Does it mean that as long as in machine mode, executing ssamoswap instrcution will cause store/AMO access fault?  Is it possible that the mstatus.mprv ==1 && mstatus.mpp == 2'b01， then the ssamoswap instruction is considered to be executed in Supervisor  mode?

**Comment by ved-rivos** [comment]
The section 2.3 defines a term called xSSE that determines if Zicfiss is enabled at a privilege mode and the table 1 shows how xSSE is determined. Instructions that are encoded using MOPs/C.MOPs are listed in section 2.1. When xSSE is 0, these revert to their ZImop/Zcmop specified behavior. The behavior of ssamoswap is specified in section 2.7 by the pseudocode in listing 2.7. When MPRV is 1 all memory accesses in M-mode are with effective privilege determined by MPP. The MPRV behavior does not change for ssamoswap,

**Comment by leBsky** [comment]
> The section 2.3 defines a term called xSSE that determines if Zicfiss is enabled at a privilege mode and the table 1 shows how xSSE is determined. Instructions that are encoded using MOPs/C.MOPs are listed in section 2.1. When xSSE is 0, these revert to their ZImop/Zcmop specified behavior. The behavior of ssamoswap is specified in section 2.7 by the pseudocode in listing 2.7. When MPRV is 1 all memory accesses in M-mode are with effective privilege determined by MPP. The MPRV behavior does not change for ssamoswap,

Close, #225 solved this.
