### ISSUE TITLE
The link in the side bar is dead

### ISSUE THREAD

**Issue by iankronquist** [riscv/riscv-cfi#230]
The side bar on github has the link [jira.riscv.org/browse/RVG-80](https://jira.riscv.org/browse/RVG-80)
It leads to a 404.
![Uploading Screenshot 2024-10-31 at 4.01.49 PM.png…]()

**Comment by ved-rivos** [comment]
@rpsene - please help.

**Comment by rpsene** [comment]
@ved-rivos  https://lf-riscv.atlassian.net/browse/RVG-80

**Comment by ved-rivos** [comment]
Thanks @rpsene !
@iankronquist - the link is updated. Thanks for reporting.
