### ISSUE TITLE
`sspush` / `sspop`: Encoding ambiguity

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-cfi#3]
Two instructions: `sspush` and `sspop` share the same encoding except:
*   `sspush`: `rs1`==source operand, `rd`==0
*   `sspop`: `rs1`==0, `rd`==destination operand

If both `rs1` and `rd` are zero, `sspush x0` and `sspop x0` are indistinguishable.

Quoting "4.1. Push to and Pop from the shadow stack":
> the CFI extension provides the `x1` and `x5` variants of the shadow stack load and store.

It (this sentence from a note) suggests that `sspush` and `sspop` only allows either `x1` or `x5` but this is not clear from the specification.

How do we resolve this?  Here are some ideas to resolve:

1.  ~~Only allow `x1` and `x5` as `sspush` and `sspop` instruction operand~~
2.  Disallow `x0` on `sspush` and `sspop` instructions (but allow other registers)
3.  ~~Use different encodings (e.g. use different `funct3`) between `sspush` and `sspop` instructions~~
4.  ~~Define the special behavior (explicitly) if an operand of `sspush` or `sspop` is `x0` (I don't like this option though)~~

**Comment by ved-rivos** [comment]
using `rd=x0` is disallowed for `sspop` and using `rs1=x0` is disallowed for `sspush`. Other registers are allowed.

**Comment by a4lg** [comment]
Thanks! (going forward with option 2)

**Comment by ved-rivos** [comment]
Thanks. Document updated.
