### ISSUE TITLE
`ssamoswap`, `lpsll` and `lpcll`: Encoding ambiguity

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-cfi#4]
Those three instructions share the same encoding space (same major opcode, funct7 and funct3):

```
ssamoswap : 1000001 src||addr 100 dst 1110011
lpsll     : 1000001   0||LLPL 100   0 1110011
lpcll     : 1000001   1||LLPL 100   0 1110011
```

and `lpsll` and `lpcll` instructions are indistinguishable from the `ssamoswap` instruction with `rd` of `x0`.

If sharing the encoding space is expected, `ssamoswap` must prohibit destination zero register.

**Comment by ved-rivos** [comment]
Yes, the use of `x0` for `ssamoswap` is not allowed.

**Comment by a4lg** [comment]
Thanks!

**Comment by ved-rivos** [comment]
Thanks. Document updated.
