### ISSUE TITLE
many bits decoding needed to differentiate `lpcll` `lpsll` and `ssamoswap` 

### ISSUE THREAD

**Issue by kacouane** [riscv/riscv-cfi#51]
I did a short implementation check in rocket-chip. 
And while adding the instructions I have an error as the only way to distinguish `ssamoswap` from `lpcll` or `lpsll` is to check the `rd` field to be precisely zero. (And because legacy rocket-chip encoding systems don't support this)

This is not a genuine issue as decoding is still possible but as the instruction encoding is still flexible it might be good to know ...

**Comment by ved-rivos** [comment]
This implementation has likely been updated to support extensions like Zihintpause and Zihintntl. I agree with your observation about not being a genuine issue. This seems more like an issue with this specific implementation.
