### ISSUE TITLE
ELP behaviour on bad target instruction

### ISSUE THREAD

**Issue by jklockars** [riscv/riscv-cfi#53]
I ran into an issue with my implementation of forward CFI which, unless I am missing something, was caused by the proposed standard being incorrect.

"When ELP is set to LP_EXPECTED and the next instruction in the instruction stream is not lpcll, then an illegal instruction exception is raised. If the next instruction in the instruction stream is lpcll then the ELP updates to NO_LP_EXPECTED."
...
"When the instructions cause an illegal-instruction exception, the ELP does not change."

The second statement means that the fault handler will be entered with ELP still set. If forward CFI is enabled in the handler's mode (I was running tests in machine mode, so there was no way to avoid that) this in turn means that the first statement requires the fault handler to begin with a matching lpcll, or you get a never-ending fault loop...

There is a later statement:
"When a trap is taken into privilege mode x, the xPELP bits are updated with current ELP and ELP is set to NO_LP_EXPECTED."
but that is in a chapter that explicitly talks about:
"A trap may need to be delivered to the same or higher privilege level on completion of JALR but before the instruction at the target of JALR was decoded..."

I suggest removing the second statement above and making it clear what the intended behaviour is when faulting due to lack of lpcll after call (or when the ID is wrong).
In my "fixed" implementation, I now _always_ clear ELP for every instruction that is not supposed to actually set it. If ELP was set before there are then three possible situations:
1 The new instruction is a correct lpcll - everything is fine
2 There was an exception so the instruction was not executed - old ELP state copied into xPELP and exception handler called
3 The new instruction was not an lpcll, or was an lpcll at an unaligned address or with wrong ID - old ELP state copied into xPELP and fault handler called.
AFAICT, that should always work fine.

It is still unclear whether xPELP is supposed to be set when faulting in case 3.
Is it useful to be able to see in the fault handler whether this was a "normal" illegal instruction or a CFI error? I suppose one can still find that out by looking at the instruction.

**Comment by ved-rivos** [comment]
The ELP is updated as follows:
- A JALR that is an indirect call or a indirect jump sets ELP to LP_EXPECTED. 
- A aligned LPCLL with LLPL matching LPL.LL sets ELP to NO_LP_EXPECTED
- A SRET updates ELP to SPELP
- A MRET updates ELP to MPELP
- A trap delivery copies ELP to xPELP and sets ELP to NO_LP_EXPECTED

When ELP is LP_EXPECTED:
- if the next instruction decoded is not an LPCLL that matches LPL.LL then  an illegal instruction occurs.

"When the instructions cause an illegal-instruction exception, the ELP does not change."
The intent here was that the ELP is stays unchanged when the previous condition occurs. The exception causes a trap to be delivered to the handler. The trap delivery moves this unchanged ELP to xPELP and sets ELP to NO_LP_EXPECTED. 

> It is still unclear whether xPELP is supposed to be set when faulting in case 3.

Yes. the behavior is correct to set the xPELP to ELP. The reason to have this ELP preserved in xPELP is to support use cases like debugging where a debugger may replace the LPCLL with a EBREAK. This will cause a trap and the debugger may then put back the LPCLL and SRET back. On the SRET the state of ELP is restored to xPELP and allows the forward CFI tracking  to continue.

> I now always clear ELP for every instruction that is not supposed to actually set it. 

This may actually be not required. If an instruction commits then ELP must be NO_LP_EXPECTED. If ELP was LP_EXPECTED then the only instruction that can commit is a LPCLL with a matching label.

Will post a PR with some updated text to make this more clear.

**Comment by ved-rivos** [comment]
Please see PR #55
