### ISSUE TITLE
`sschkra`: strange encoding or operand ordering

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-cfi#6]
Despite that `sschkra` is encoded as `rs1==5` and `rs2==1`, the only example of this instruction shows: `sschkra x1, x5`.
If two operands are encoded as `rs1` and `rs2`, it usually means `rs1==1` and `rs2==5`.  This is rather strange.

Changing encoding and/or operands of this instruction may be required.
Note that not all options are mutually exclusive (e.g. 1 and 3 are not mutually exclusive).

1.  ~~Change encoding of `sschkra` so that `rs1==1` and `rs2==5`.~~
2.  Accept only `sschkra x5, x1` and change the example in the specification.
3.  ~~Accept both `sschkra x1, x5` and `sschkra x5, x1`, assign them the same opcode.~~
4.  ~~Remove both operands from the assembler mnemonics of `sschkra` (to encode `sschkra` instruction with just `sschkra`, not `sschkra x1, x5` or something) and make `x1` and `x5` implicit.~~

~~Note that `sschkra` instruction shares the same major opcode, funct7 and funct3 with `lpsul` and `lpcul` instructions but it is safe to swap `(rs1,rs2)==(5,1) → (1,5)` as in option 1 because doing so does not cause crash to `lpsul` and `lpcul` instructions (to NOT crash with `lpsul` and `lpcul`, register number of `rs2` must be less than 16).~~

**Comment by ved-rivos** [comment]
So `lpsul`/`lpcul` use funct7 of `1000011` while `sschkra` uses `1000101` so there is no crash between them. 
The example should be fixed to match the intended encoding.

**Comment by a4lg** [comment]
Thanks! (going forward with option 2)

> So `lpsul`/`lpcul` use funct7 of `1000011` while `sschkra` uses `1000101` so there is no crash between them.

It conflicts with the specification document.  It seems the document is wrong.  I submitted the fix (#7).

**Comment by ved-rivos** [comment]
Thanks for the PR. Doc updated with example fixed.
