### ISSUE TITLE
Editorial; "allowing preserving" incorrect

### ISSUE THREAD

**Issue by deanliberty5** [riscv/riscv-cfi#69]
In the sentence "Operating in shadow stack mode, i.e., where the call stack layout is preserved and the shadow stack is used to store a shadow copy of the link register, allowing preserving the ABI", the phrase "allowing preserving" should be replaced with "preserving" or "allows preserving".

**Comment by ved-rivos** [comment]
Updates in https://github.com/riscv/riscv-cfi/pull/72/commits
