### ISSUE TITLE
sspmp description

### ISSUE THREAD

**Issue by deanliberty5** [riscv/riscv-cfi#75]
The following text still has the problematic description of 'sspmp', which was fixed in earlier text:

"When the Smepmp extension is implemented, a new WARL field sspmp is defined in the mseccfg CSR **to
configure a PMP entry** as the shadow stack memory region for M-mode accesses."

Instead of "to configure a PMP entry", I think words like "to identify a PMP entry" (used earlier in the spec) are clearer.

**Comment by ved-rivos** [comment]
Updates in https://github.com/riscv/riscv-cfi/pull/73
