### ISSUE TITLE
Prerequisites and dependencies

### ISSUE THREAD

**Issue by deanliberty5** [riscv/riscv-cfi#89]
I just realized that smepmp might be a prerequisite for SS and LP.  It is not stated explicitly.  Could you please include a list of perquisites and dependencies?

Thanks.

**Comment by ved-rivos** [comment]
Priv: Smepmp and Sv39/Sv48/Sv57
Unpriv: Zicsr, Ziccif, Ziccamoa, A, and C

**Comment by ved-rivos** [comment]
Updated extension dependencies list in PR #90 with latest updates (Zcmop, compressed cfi insts, Ziccamoa) and the missing list of priv extensions.

**Comment by deanliberty5** [comment]
Ved, before we close this issue, I'd like to probe a little more.
**Why** is there a dependency on smepmp?  What is it in smepmp that we require?

**Comment by ved-rivos** [comment]
Smepmp introduces mseccfg CSR. The Zisslpcfi adds a field in this CSR. Zisslpcfi can be implemented without Smepmp, however without Smepmp, the shadow stack memory protection is not present. 

> 
> When the `Smepmp` extension is implemented, a new WARL field `sspmp` is defined
> in the `mseccfg` CSR to identify a PMP entry as the shadow stack memory region
> for M-mode accesses.
> 
> When `sspmp` field is implemented and `mseccfg.MML` is 1 the following rules are
> additionally enforced for M-mode memory accesses:
> 
> * `sspush`, `c.sspush`, `sspop`, `sspopchk`, `c.sspopchk`, and `ssamoswap`
>   instructions must match PMP entry `sspmp`.
> 
> * Write by instructions other than `sspush`, `c.sspush`, and `ssamoswap` that
>   match PMP entry `sspmp` cause an access violation exception.

**Comment by ved-rivos** [comment]
Though it is possible to make dependence only on the `mseccfg` CSR and not the rest of the `Smepmp`.

**Comment by deanliberty5** [comment]
Yes, that is the dependency we would prefer to see.  

I am sitting here reading about MML, to make sure I have not overlooked anything.  We obviously need the encoding of pmpcfg.RW=01.

**Comment by ved-rivos** [comment]
The `MML` if implemented would write protect `sspmp` field. The protection itself should not be dependent on `MML` - only whether `sspmp` field is implemented. See https://github.com/riscv/riscv-cfi/pull/90/commits
