### ISSUE TITLE
State leakage and burden of clearing of CSRs even if it's not enabled

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-cfi#9]
LPLR and SSP CSRs are unprivileged CSRs and their access is gated via menvcfg.CFI and henvcfg.CFI

IIRC, earlier these CSR accesses were gated via xcfistatus enable bits. Thus any access to SSP/LPLR CSRs in U mode (if not enabled) would've led to illegal instruction fault.

As per current spec, to prevent leakage; LPLR/SSP need to be context switched unconditionally whether a mode/u mode task has it enabled or not (because access to the CSR is allowed).

Is this intentional?

**Comment by ved-rivos** [comment]
This was missed. When `sstatus.UFCFIEN` is 0 then `lplr` access in U-mode should cause illegal inst. exception and when `sstatus.UBCFIEN` is 0 then `ssp` access in U-mode should cause illegal inst. exception. This allows a supervisor (if `menvcfg.CFI` is 1) to switch these CSRs without needing to have supervisor CFI enabled but prevents user mode from accessing the CSRs when user CFI is not enabled. PR #16
