### ISSUE TITLE
CSR lpl accessibility for U-mode

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-cfi#92]
Spec says:
> When menvcfg.CFIE is 0, an attempt to access `lpl` in a mode other than M-mode raises an illegal instruction exception.

However, it didn't mention the accessibility of U-mode when menvcfg.CFIE is 1. Is it managed by the sstatus.UFCFIE?

**Comment by ved-rivos** [comment]
The `lpl` CSR is a supervisor read-write (SRW) 32-bit register. When `menvcfg.CFIE` is 1, it can be accessed in S/HS-mode. When `menvcfg.CFIE` and `henvcfg.CFIE` are both 1, it can accessed in VS-mode. It is not accessible at U-mode as a CSR.

**Comment by henry-hsieh** [comment]
Oh! I missed the SRW attribute. Thanks for the explanation.
